export enum ERROR_CODES {
  MINIGIT_PATH_NOT_FOUND_ERROR = "MINIGIT_PATH_NOT_FOUND_ERROR",
  INVALID_COMMAND_ERROR = "INVALID_COMMAND_ERROR",
  OBJECT_NOT_FOUND_ERROR = "OBJECT_NOT_FOUND_ERROR",
  OBJECT_CORRUPTED_ERROR = "OBJECT_CORRUPTED_ERROR",
  INDEX_NOT_FOUND_ERROR = "INDEX_NOT_FOUND_ERROR",
  INDEX_CORRUPTED_ERROR = "INDEX_CORRUPTED_ERROR",
  DIRECTORY_NOT_FOUND_ERROR = "DIRECTORY_NOT_FOUND_ERROR",
  FILE_NOT_FOUND_ERROR = "FILE_NOT_FOUND_ERROR",
  ERR_MODULE_NOT_FOUND = "ERR_MODULE_NOT_FOUND"
}
